/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SCI.centraltoko.gui.master;

import com.SCI.centraltoko.gui.laporan.LaporanPembelian;
import com.SCI.centraltoko.gui.security.FrmLogin;
import com.SCI.centraltoko.gui.transaksi.FrmPembelian;
import com.SCI.centraltoko.gui.transaksi.FrmPenjualan;
import com.SCI.centraltoko.model.Person;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.ImageIcon;


import javax.swing.JFrame;


/**
 *
 * @author yuzri
 */
public class MainFrame extends javax.swing.JFrame {

    public static ImageIcon icon= new ImageIcon("src/com/SCI/centraltoko/icon/Linux-icon.png");
    private static final ImageIcon image =new ImageIcon("src/com/SCI/centraltoko/icon/202.jpg");
    private Person person;
    
    
    /**
     * Creates new form MainFrame
     */
    private static final org.jboss.logging.Logger log=org.jboss.logging.Logger.getLogger(MainFrame.class);
    
    public MainFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        incoFrame();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bagroundImage1 = new com.SCI.centraltoko.utility.BagroundImage();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenu3.setText("Master");

        jMenuItem1.setText("Person");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator7);

        jMenuItem2.setText("Produk");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator5);

        jMenu4.setText("Transaksi");

        jMenuItem3.setText("Pembelian");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);
        jMenu4.add(jSeparator6);

        jMenuItem4.setText("Penjualan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator3);

        jMenuItem5.setText("Login");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/kecil/delete-2.png"))); // NOI18N
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laporan");

        jMenuItem7.setText("Pembelian");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator1);

        jMenuItem8.setText("Penjualan");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagroundImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagroundImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    Deklarasi form person
    public FrmPerson frmPerson;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try{
            if(frmPerson==null){
                frmPerson=new FrmPerson();
               bagroundImage1.add(frmPerson);
                Dimension parentSize= bagroundImage1.getSize();
                Dimension childSize=frmPerson.getSize();
               frmPerson.setLocation((parentSize.width-childSize.width)/2,(parentSize.height-childSize.height)/2);
            }else{
                frmPerson.toFront();
            }
            frmPerson.setVisible(true);
            frmPerson.setSelected(true);
         
        }catch(PropertyVetoException ex){
           log.error("Gagal Meload frmPerson", ex);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    public FrmProduk frmProduk;
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
            if(frmProduk==null){
                frmProduk=new FrmProduk();
                bagroundImage1.add(frmProduk);
                Dimension parentSize=bagroundImage1.getSize();
                Dimension childSize=frmProduk.getSize();
               frmProduk.setLocation((parentSize.width-childSize.width)/2, (parentSize.height-childSize.height)/2);
            }else{
                frmProduk.toFront();
            }
            frmProduk.setVisible(true);
            frmProduk.setSelected(true);
        }catch(PropertyVetoException ex){
            log.error("Gagal meload frameProduk", ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public FrmPembelian frmPembelian;
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //TODO add your handling code here:
        try{
            if(frmPembelian==null){
                frmPembelian=new FrmPembelian();
               bagroundImage1.add(frmPembelian);
               Dimension parentSize=bagroundImage1.getSize();
                Dimension childSize=frmPembelian.getSize();
                frmPembelian.setLocation((parentSize.width-childSize.width)/2,(parentSize.height-childSize.height)/2);
            }else{
                frmPembelian.toFront();
            }
            frmPembelian.setVisible(true);
            frmPembelian.setSelected(true);
        }catch(PropertyVetoException ex){
            log.error("Gagal menampilkan FrmPembelian", ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    public FrmPenjualan frmPenjualan;
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try{
            if(frmPenjualan==null){
                frmPenjualan=new FrmPenjualan();
                bagroundImage1.add(frmPenjualan);
                Dimension parentSize=bagroundImage1.getSize();
                Dimension childSize= frmPenjualan.getSize();
               frmPenjualan.setLocation((parentSize.width-childSize.width)/2, (parentSize.height-childSize.height)/2);
            }else{
                frmPenjualan.toFront();
            }
            frmPenjualan.setVisible(true);
            frmPenjualan.setSelected(true);
        }catch(PropertyVetoException ex){
            log.error("Gagal meload frmPejualan", ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Person p = new FrmLogin().showDialog();
        if(p != null){
            person=p;
          //  lblNama.setText(person.getNama());
            isiLabelFoto();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    public LaporanPembelian laporanPembelian;
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try{ 
            if(laporanPembelian==null){
                laporanPembelian=new LaporanPembelian();
                bagroundImage1.add(laporanPembelian);
            }else{
                laporanPembelian.toFront();
            }
            laporanPembelian.setVisible(true);
            laporanPembelian.setSelected(true);
            laporanPembelian.setSize(bagroundImage1.getSize());
        }catch(PropertyVetoException exception){
            log.error("Gagal meload Form LaporanPembelian", exception);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    
   
public final void incoFrame(){
    
    setIconImage(icon.getImage());
}
public void isiLabelFoto(){
    if(person.getPicture() !=null){
        try{
            ObjectInputStream inputStream=new ObjectInputStream(new ByteArrayInputStream(person.getPicture()));
            ImageIcon img= (ImageIcon) inputStream.readObject();
           // lblFoto.setIcon(img);
        }catch(ClassNotFoundException cnfe){
         log.error("Gagal mengubah array to picture", cnfe);
        }catch(IOException ioe){
            log.error("Gagal meload picture", ioe);
        }
    }else{
        //lblFoto.setIcon(null);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.SCI.centraltoko.utility.BagroundImage bagroundImage1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
