/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SCI.centraltoko.gui.lookup;

import com.SCI.centraltoko.Main;
import com.SCI.centraltoko.model.transaksi.Pembelian;
import com.SCI.centraltoko.utility.UtilityTools;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author yuzri
 */
public class PembelianSearchDialog extends javax.swing.JDialog {

    private List<Pembelian> pembelians;
    private Pembelian selectedPembelian;
    private boolean isOk=false;
    
    /**
     * Creates new form PembelianSearchDialog
     */
    public PembelianSearchDialog() {
        super(Main.getFrame(), true);
        initComponents();
        setLocationRelativeTo(null);
        tblPembelian.setAutoCreateColumnsFromModel(false);
        tblPembelian.getSelectionModel().addListSelectionListener(new TabelPembelianListener());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembelian = new javax.swing.JTable();
        btnBatal = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cari");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblPembelian);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Cancel.png"))); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Ok.png"))); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"IndexOfReplaceableByContains", "RedundantStringToString"})
    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
      for(int i=0;i<tblPembelian.getRowCount();i++){
          String current=tblPembelian.getValueAt(i, 0).toString();
          if(current.toLowerCase().indexOf(txtCari.getText().toLowerCase())>=0){
              tblPembelian.getSelectionModel().setSelectionInterval(i, i);
              tblPembelian.getColumnModel().getSelectionModel().setSelectionInterval(0, 0);
              UtilityTools.scroolTorect(tblPembelian, i);
              break;
          }
      }
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if(selectedPembelian !=null){
            isOk=true;
            dispose();
        }else{
            JOptionPane.showMessageDialog(Main.getFrame(), "Pilih Pembelian", "ERROR",JOptionPane.ERROR_MESSAGE,Main.getFrame().icon );
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        selectedPembelian=null;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public Pembelian showDialog(){
        pembelians=Main.getTransaksiService().semuaPembelian();
        tblPembelian.setModel(new TabelModelPenjualan());
        setVisible(true);
        if(isOk==false) selectedPembelian=null;
        return selectedPembelian;
    } 
    private class TabelModelPenjualan extends AbstractTableModel{

        @Override
        public int getRowCount() {
         return pembelians.size();
        }

        @Override
        public int getColumnCount() {
            return 3;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Pembelian p = pembelians.get(rowIndex);
            switch(columnIndex){
                case 0 : return p.getId();
                case 1 : return p.getTgl_beli();
                case 2 : return p.getTotal();
                default : return "";
            }
        }
        
    }
    
    private class TabelPembelianListener implements ListSelectionListener{

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if(tblPembelian.getSelectedRow()>=0){
                int index=tblPembelian.convertRowIndexToModel(tblPembelian.getSelectedRow());
                selectedPembelian=pembelians.get(index);
            }
        }
        
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPembelian;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
