/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SCI.centraltoko.gui.lookup;

import com.SCI.centraltoko.Main;
import com.SCI.centraltoko.model.Produk;
import com.SCI.centraltoko.model.transaksi.PembelianDetail;
import com.SCI.centraltoko.utility.UtilityTools;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author yuzri
 */
public class PembelianLooKDialog extends javax.swing.JDialog {

    /**
     * Creates new form PembelianLooKDialog
     */
    private PembelianDetail detail;
    private Produk selectedProduk;
    private Integer jumlah=0;
    private Integer editJumlah;
    private final ImageIcon icon= new ImageIcon("src/com/SCI/centraltoko/icon/Linux-icon.png");
    public PembelianLooKDialog() {
        super(Main.getFrame(), true);
        initComponents();
        setLocationRelativeTo(null);
        
        UtilityTools.setCurrency(txtH);
        UtilityTools.setNumericTextOnly(txtQ);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        txtH = new javax.swing.JTextField();
        txtQ = new javax.swing.JTextField();
        txtST = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produk");

        jLabel2.setText("Harga Beli");

        jLabel3.setText("Quantity");

        jLabel4.setText("Sub Total");

        txtH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHKeyReleased(evt);
            }
        });

        txtQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQKeyReleased(evt);
            }
        });

        txtST.setEnabled(false);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(txtST, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnBatal))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if(validasiForm()){
            if(detail==null) detail=new PembelianDetail();
            loadFormToModel();
            dispose();
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        detail=null;
         dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Produk p= new ProdukLookDialog().showDialog();
        if(p != null){
            selectedProduk=p;
           
            txtProduk.setText(selectedProduk.getNama());
             
            txtH.setText(UtilityTools.formatNumber(p.gethBeli()));
            editJumlah=selectedProduk.getStok();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHKeyReleased
        // TODO add your handling code here:
        calculateSubTotal();
    }//GEN-LAST:event_txtHKeyReleased

    private void txtQKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQKeyReleased
        // TODO add your handling code here:
        calculateSubTotal();
       
    }//GEN-LAST:event_txtQKeyReleased

    /**
     * @param args the command line arguments
     */
    public  PembelianDetail showDialog(){
        setVisible(true);
        return detail;
    }
    
    public PembelianDetail showDialog(PembelianDetail detail){
        this.detail=detail;
        loadModelToForm();
        Integer jml=detail.getJumlah();
        editJumlah=detail.getProduk().getStok()-jml;
        setVisible(true);
        return this.detail;
    }
    
    private void loadModelToForm(){
        selectedProduk=detail.getProduk();
        txtProduk.setText(selectedProduk.getNama());
        txtQ.setText(detail.getJumlah().toString());
        txtH.setText(UtilityTools.formatNumber(detail.getHarga()));
        txtST.setText(UtilityTools.formatNumber(detail.getSubTotal()));
    }
  private void loadFormToModel(){
      hitungStok();
      detail.setProduk(selectedProduk);
      detail.setJumlah(Integer.valueOf(txtQ.getText()));
      detail.setHarga(UtilityTools.parseNumberToBigDecimal(txtH.getText()));
      detail.setSubTotal(UtilityTools.parseNumberToBigDecimal(txtST.getText()));
  }
  private boolean validasiForm(){
      if(txtProduk.getText().length()==0 || selectedProduk==null){
          JOptionPane.showMessageDialog(Main.getFrame(), "Pilih Produk","ERROR", JOptionPane.ERROR_MESSAGE, icon);
          return false;
      }
      if(txtH.getText().length()==0){
          JOptionPane.showMessageDialog(Main.getFrame(), "Isi Harga", "ERROR", JOptionPane.ERROR_MESSAGE, icon);
          return false;
      }
      if(txtQ.getText().length()==0 || Integer.valueOf(txtQ.getText())<=0){
          JOptionPane.showMessageDialog(Main.getFrame(), "Isi Quantity", "ERROR", JOptionPane.ERROR_MESSAGE, icon);
          return false;
      }
      return true;
  }
  
  private void calculateSubTotal(){
      if(txtH.getText().length()>0 &&  txtQ.getText().length()>0){
          BigDecimal harga=UtilityTools.parseNumberToBigDecimal(txtH.getText());
          Integer qty=Integer.valueOf(txtQ.getText());
          BigDecimal subTotal=harga.multiply(new BigDecimal(qty));
          txtST.setText(UtilityTools.formatNumber(subTotal));
      }
  }
  private Integer hitungStok(){
      if(selectedProduk !=null){
      Integer jmlH=Integer.valueOf(txtQ.getText());
      jumlah=editJumlah + jmlH;
      selectedProduk.setStok(jumlah);
      selectedProduk.sethBeli(UtilityTools.parseNumberToBigDecimal(txtH.getText()));
      }
      return jumlah;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtQ;
    private javax.swing.JTextField txtST;
    // End of variables declaration//GEN-END:variables
}
