/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SCI.centraltoko.gui.lookup;

import com.SCI.centraltoko.Main;
import com.SCI.centraltoko.model.Produk;
import com.SCI.centraltoko.model.transaksi.PenjualanDetail;
import com.SCI.centraltoko.utility.UtilityTools;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author yuzri
 */
public class PenjualanAddDialog extends javax.swing.JDialog {

    private PenjualanDetail detail;
    private Produk selectedProduk;
    private final ImageIcon icon= new ImageIcon("src/com/SCI/centraltoko/icon/Linux-icon.png");
    private Integer kurangStok;
    private Integer jumlah;
    
    /**
     * Creates new form PenjualanAddDialog
     */
    public PenjualanAddDialog() {
        super(Main.getFrame(), true);
        initComponents();
        setLocationRelativeTo(null);
        UtilityTools.setCurrency(txtHarga);
        UtilityTools.setCurrency(txtS);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produk");

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Search.png"))); // NOI18N
        btnCari.setToolTipText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel2.setText("Harga");

        jLabel3.setText("Quantity");

        txtQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQKeyReleased(evt);
            }
        });

        jLabel4.setText("Sub Total");

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Ok.png"))); // NOI18N
        btnOk.setToolTipText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Cancel.png"))); // NOI18N
        btnBatal.setToolTipText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCari)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Produk p = new ProdukLookDialog().showDialog();
        if(p !=null){
            selectedProduk=p;
            txtNama.setText(selectedProduk.getNama());
            txtHarga.setText(UtilityTools.formatNumber(selectedProduk.gethJual()));
            kurangStok=selectedProduk.getStok();
            
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtQKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQKeyReleased
        // TODO add your handling code here:
        calculate();
    }//GEN-LAST:event_txtQKeyReleased

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            if(detail==null) detail=new PenjualanDetail();
            loadFormToModel();
            dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        detail=null;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public PenjualanDetail showDialog(){
        setVisible(true);
        return detail;
    }
    public PenjualanDetail showDialog(PenjualanDetail detail){
        this.detail=detail;
        loadModelToForm();
        Integer jml=detail.getJumlah();
        kurangStok=detail.getProduk().getStok()+jml;
        setVisible(true);
        return this.detail;
    }

    private void calculate(){
        if(txtHarga.getText().length()>0 && txtQ.getText().length()>0){
            BigDecimal harga=UtilityTools.parseNumberToBigDecimal(txtHarga.getText());
            Integer jml=Integer.valueOf(txtQ.getText());
            BigDecimal total=harga.multiply(new BigDecimal(jml));
            txtS.setText(UtilityTools.formatNumber(total));
        }
        
    }
    
    private void loadModelToForm(){
        selectedProduk=detail.getProduk();
        txtNama.setText(selectedProduk.getNama());
        txtHarga.setText(UtilityTools.formatNumber(selectedProduk.gethJual()));
        txtQ.setText(detail.getJumlah().toString());
        txtS.setText(UtilityTools.formatNumber(detail.getSubTotal()));
    }
    private void loadFormToModel(){
        hitungStok();
        detail.setProduk(selectedProduk);
        detail.setHarga(UtilityTools.parseNumberToBigDecimal(txtHarga.getText()));
        detail.setJumlah(Integer.valueOf(txtQ.getText()));
        detail.setSubTotal(UtilityTools.parseNumberToBigDecimal(txtS.getText()));
    }
    
    private boolean validateForm(){
        if(txtNama.getText().length()==0 || selectedProduk==null){
            JOptionPane.showMessageDialog(Main.getFrame(),"Pilih produk","ERROR",JOptionPane.ERROR_MESSAGE, icon);
            return false;
        }
        if(txtHarga.getText().length()==0){
            JOptionPane.showMessageDialog(Main.getFrame(),"Isi harga", "ERROR", JOptionPane.ERROR_MESSAGE, icon);
            return false;
        }
        if(txtQ.getText().length()==0 ){
            JOptionPane.showMessageDialog(Main.getFrame(),"Isi quantity","ERROR",JOptionPane.ERROR_MESSAGE, icon);
            return false;
        }
        
        return true;
    }
    private void hitungStok(){
        if(selectedProduk !=null){
            Integer jml=Integer.valueOf(txtQ.getText());
            jumlah=kurangStok-jml;
            selectedProduk.setStok(jumlah);
        }
        jumlah=0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtQ;
    private javax.swing.JTextField txtS;
    // End of variables declaration//GEN-END:variables
}
