/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SCI.centraltoko.gui.transaksi;

import com.SCI.centraltoko.Main;
import com.SCI.centraltoko.gui.lookup.PenjualanAddDialog;
import com.SCI.centraltoko.gui.lookup.PenjualanSearchDialog;
import com.SCI.centraltoko.model.transaksi.Penjualan;
import com.SCI.centraltoko.model.transaksi.PenjualanDetail;
import com.SCI.centraltoko.utility.UtilityTools;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.AbstractTableModel;
import org.hibernate.StaleObjectStateException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author yuzri
 */
public class FrmPenjualan extends javax.swing.JInternalFrame {

    @SuppressWarnings("Convert2Diamond")
    private List<PenjualanDetail> listDetails=new ArrayList<PenjualanDetail>();
    private PenjualanDetail selectedPenjualan;
    private Penjualan penjualan;
    private static final Logger log =LoggerFactory.getLogger(FrmPenjualan.class);
    /**
     * Creates new form FrmPenjualan
     */
    public FrmPenjualan() {
        initComponents();
        
        tblPenjualan.setAutoCreateColumnsFromModel(false);
        tblPenjualan.getSelectionModel().addListSelectionListener(new TabelPenjualanListener());
        UtilityTools.setCurrency(txtBayar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtTGL = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        btnTambahP = new javax.swing.JButton();
        btnEditP = new javax.swing.JButton();
        btnHapusP = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Add.png"))); // NOI18N
        btnTambah.setToolTipText("Tambah");
        btnTambah.setFocusable(false);
        btnTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambah.setMargin(new java.awt.Insets(0, 4, 0, 4));
        btnTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTambah);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Save.png"))); // NOI18N
        btnSimpan.setToolTipText("Simpan");
        btnSimpan.setFocusable(false);
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMargin(new java.awt.Insets(0, 6, 0, 4));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Edit page.png"))); // NOI18N
        btnEdit.setToolTipText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setMargin(new java.awt.Insets(0, 6, 0, 4));
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEdit);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Delete.png"))); // NOI18N
        btnHapus.setToolTipText("Hapus");
        btnHapus.setFocusable(false);
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setMargin(new java.awt.Insets(0, 6, 0, 4));
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHapus);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Search.png"))); // NOI18N
        btnCari.setToolTipText("Cari");
        btnCari.setFocusable(false);
        btnCari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCari.setMargin(new java.awt.Insets(0, 6, 0, 4));
        btnCari.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCari);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Cancel.png"))); // NOI18N
        btnBatal.setToolTipText("Batal");
        btnBatal.setFocusable(false);
        btnBatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBatal.setMargin(new java.awt.Insets(0, 6, 0, 4));
        btnBatal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBatal);

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Back.png"))); // NOI18N
        btnKeluar.setToolTipText("Keluar");
        btnKeluar.setFocusable(false);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setMargin(new java.awt.Insets(0, 6, 0, 0));
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKeluar);

        jLabel1.setText("ID");

        jLabel2.setText("TGL Penjualan");

        jLabel3.setText("Total");

        jLabel4.setText("Bayar");

        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayarKeyReleased(evt);
            }
        });

        jLabel5.setText("Kembali");

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produk", "Harga", "Quantity", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        btnTambahP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/kecil/add.png"))); // NOI18N
        btnTambahP.setText("Tambah");
        btnTambahP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPActionPerformed(evt);
            }
        });

        btnEditP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/kecil/document.png"))); // NOI18N
        btnEditP.setText("Edit");
        btnEditP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPActionPerformed(evt);
            }
        });

        btnHapusP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/kecil/delete-2.png"))); // NOI18N
        btnHapusP.setText("Hapus");
        btnHapusP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambahP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusP)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))))
                    .addComponent(txtTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahP)
                    .addComponent(btnEditP)
                    .addComponent(btnHapusP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPActionPerformed
        // TODO add your handling code here:
        PenjualanDetail p=new PenjualanAddDialog().showDialog();
        if(p!=null){
            listDetails.add(p);
            tblPenjualan.setModel(new TabelPenjualanModel());
            calculate();
        }
    }//GEN-LAST:event_btnTambahPActionPerformed

    private void btnEditPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPActionPerformed
        // TODO add your handling code here:
        if(selectedPenjualan != null){
            selectedPenjualan=new PenjualanAddDialog().showDialog(selectedPenjualan);
            tblPenjualan.tableChanged(new TableModelEvent(tblPenjualan.getModel(), tblPenjualan.getSelectedRow()));
            calculate();
        }else{
            JOptionPane.showMessageDialog(Main.getFrame(),"Pilih penjualan", "WARNING",JOptionPane.WARNING_MESSAGE,getFrameIcon());
        }
    }//GEN-LAST:event_btnEditPActionPerformed

    private void btnHapusPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPActionPerformed
        // TODO add your handling code here:
        if(selectedPenjualan !=null){
            listDetails.remove(selectedPenjualan);
            tblPenjualan.setModel(new TabelPenjualanModel());
            calculate();
            selectedPenjualan=null;
        }else{
            JOptionPane.showMessageDialog(Main.getFrame(),"Pilih penjualan","WARNING",JOptionPane.WARNING_MESSAGE, getFrameIcon());
        }
    }//GEN-LAST:event_btnHapusPActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        txtTGL.setDate(new Date());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(penjualan==null) penjualan=new Penjualan();
        loadFormToModel();
        try{
            Main.getTransaksiService().simpan(penjualan);
        }catch(StaleObjectStateException ex){
            JOptionPane.showMessageDialog(Main.getFrame(), "Data sudah di Update user lain","WARNING" ,JOptionPane.WARNING_MESSAGE, getFrameIcon());
            log.error("Gagal simpan data penjualan", ex);
        }
        
        penjualan=null;
        bersih();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        Main.getFrame().frmPenjualan=null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        Main.getFrame().frmPenjualan=null;
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyReleased
        // TODO add your handling code here:
        if(txtTotal.getText().length()>0 && txtBayar.getText().length()>0){
            BigDecimal harga=UtilityTools.parseNumberToBigDecimal(txtTotal.getText());
            BigDecimal bayar=UtilityTools.parseNumberToBigDecimal(txtBayar.getText());
            BigDecimal kembali=bayar.subtract(harga);
            txtKembali.setText(UtilityTools.formatNumber(kembali));
        }
    }//GEN-LAST:event_txtBayarKeyReleased

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Penjualan p= new PenjualanSearchDialog().showDialog();
        if(p !=null){
            penjualan=Main.getTransaksiService().getIdPenjualan(p.getId());
            loadModelToForm();
        }
    }//GEN-LAST:event_btnCariActionPerformed


    private class TabelPenjualanModel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return listDetails.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            PenjualanDetail p = listDetails.get(rowIndex);
            
            switch(columnIndex){
                case 0 : return p.getProduk().getNama();
                case 1 : return p.getHarga();
                case 2 : return p.getJumlah();
                case 3 : return p.getSubTotal();
                default : return "";
            }
        }
        
    }
    
    private class TabelPenjualanListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if(tblPenjualan.getSelectedRow()>=0){
                int index=tblPenjualan.convertRowIndexToModel(tblPenjualan.getSelectedRow());
                selectedPenjualan=listDetails.get(index);
                
            }
        }
        
    }
    
    private void loadFormToModel(){
        penjualan.setTglJual(txtTGL.getDate());
        penjualan.setTotal(UtilityTools.parseNumberToBigDecimal(txtTotal.getText()));
        penjualan.setPenjualanDetail(listDetails);
    }
    private void loadModelToForm(){
        txtID.setText(String.valueOf(penjualan.getId()));
        txtTGL.setDate(penjualan.getTglJual());
        txtTotal.setText(UtilityTools.formatNumber(penjualan.getTotal()));
        listDetails=penjualan.getPenjualanDetail();
        tblPenjualan.setModel(new TabelPenjualanModel());
    }
    
    private void calculate(){
        BigDecimal total=BigDecimal.ZERO;
        for(PenjualanDetail p : listDetails){
            total=total.add(p.getSubTotal());
        }
        txtTotal.setText(UtilityTools.formatNumber(total));
    }
    
    private void bersih(){
        txtID.setText("");
        txtTGL.setDate(null);
        txtTotal.setText("");
        txtBayar.setText("");
        txtKembali.setText("");
        listDetails.clear();
        tblPenjualan.setModel(new TabelPenjualanModel());
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditP;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusP;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKembali;
    private com.toedter.calendar.JDateChooser txtTGL;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
