/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SCI.centraltoko.gui.transaksi;

import com.SCI.centraltoko.Main;
import com.SCI.centraltoko.gui.lookup.PembelianLooKDialog;
import com.SCI.centraltoko.gui.lookup.PembelianSearchDialog;
import com.SCI.centraltoko.model.transaksi.Pembelian;
import com.SCI.centraltoko.model.transaksi.PembelianDetail;
import com.SCI.centraltoko.utility.POSTableCellRenderer;
import com.SCI.centraltoko.utility.UtilityTools;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.AbstractTableModel;
import org.hibernate.StaleObjectStateException;
import org.jboss.logging.Logger;

/**
 *
 * @author yuzri
 */
public class FrmPembelian extends javax.swing.JInternalFrame {

    @SuppressWarnings("Convert2Diamond")
    private List<PembelianDetail> details=new ArrayList<PembelianDetail>();
    private Pembelian pembelian;
    private PembelianDetail selectedPembelian;
    private static final Logger log=Logger.getLogger(FrmPembelian.class);
    
    /**
     * Creates new form FrmPembelian
     */
    public FrmPembelian() {
        initComponents();
        
        tblPembelian.setAutoCreateColumnsFromModel(false);
        tblPembelian.getSelectionModel().addListSelectionListener(new TabelDetailListener());
        tblPembelian.setDefaultRenderer(Object.class, new POSTableCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnTambahP = new javax.swing.JButton();
        btnSimpanP = new javax.swing.JButton();
        btnEditP = new javax.swing.JButton();
        btnHapusP = new javax.swing.JButton();
        btnCariP = new javax.swing.JButton();
        btnBatalP = new javax.swing.JButton();
        btnKeluarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtTGL = new com.toedter.calendar.JDateChooser();
        btnTambahPD = new javax.swing.JButton();
        btnEditPD = new javax.swing.JButton();
        btnHapusPD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembelian = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnTambahP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Create.png"))); // NOI18N
        btnTambahP.setText("Tambah");
        btnTambahP.setFocusable(false);
        btnTambahP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambahP.setMargin(new java.awt.Insets(0, 4, 0, 4));
        btnTambahP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTambahP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTambahP);

        btnSimpanP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Save.png"))); // NOI18N
        btnSimpanP.setText("Simpan");
        btnSimpanP.setFocusable(false);
        btnSimpanP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpanP.setMargin(new java.awt.Insets(0, 4, 0, 4));
        btnSimpanP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpanP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSimpanP);

        btnEditP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Edit page.png"))); // NOI18N
        btnEditP.setText("   Edit    ");
        btnEditP.setFocusable(false);
        btnEditP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditP.setMargin(new java.awt.Insets(0, 4, 0, 4));
        btnEditP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditP);

        btnHapusP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Delete.png"))); // NOI18N
        btnHapusP.setText("Hapus");
        btnHapusP.setFocusable(false);
        btnHapusP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapusP.setMargin(new java.awt.Insets(0, 4, 0, 4));
        btnHapusP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapusP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHapusP);

        btnCariP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Search.png"))); // NOI18N
        btnCariP.setText("  Cari    ");
        btnCariP.setFocusable(false);
        btnCariP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCariP.setMargin(new java.awt.Insets(0, 4, 0, 4));
        btnCariP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCariP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCariP);

        btnBatalP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Cancel.png"))); // NOI18N
        btnBatalP.setText(" Batal ");
        btnBatalP.setFocusable(false);
        btnBatalP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBatalP.setMargin(new java.awt.Insets(0, 4, 0, 4));
        btnBatalP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBatalP);

        btnKeluarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/toolbar/Back.png"))); // NOI18N
        btnKeluarP.setText("    Keluar   ");
        btnKeluarP.setFocusable(false);
        btnKeluarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluarP.setMargin(new java.awt.Insets(0, 4, 0, 0));
        btnKeluarP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKeluarP);

        jLabel1.setText("ID");

        jLabel2.setText("Total");

        jLabel3.setText("TGL Pembelian");

        txtID.setEnabled(false);

        txtTotal.setEnabled(false);

        txtTGL.setEnabled(false);

        btnTambahPD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/kecil/add.png"))); // NOI18N
        btnTambahPD.setText("Tambah");
        btnTambahPD.setEnabled(false);
        btnTambahPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPDActionPerformed(evt);
            }
        });

        btnEditPD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/kecil/document.png"))); // NOI18N
        btnEditPD.setText("Edit");
        btnEditPD.setEnabled(false);
        btnEditPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPDActionPerformed(evt);
            }
        });

        btnHapusPD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SCI/centraltoko/icon/kecil/delete-2.png"))); // NOI18N
        btnHapusPD.setText("Hapus");
        btnHapusPD.setEnabled(false);
        btnHapusPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPDActionPerformed(evt);
            }
        });

        tblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produk", "Harga Beli", "Quantity", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(tblPembelian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambahPD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditPD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapusPD)))
                        .addGap(0, 179, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahPD)
                    .addComponent(btnEditPD)
                    .addComponent(btnHapusPD))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPDActionPerformed
        // TODO add your handling code here:
        PembelianDetail p = new PembelianLooKDialog().showDialog();
        if(p !=null){
            details.add(p);
            
            tblPembelian.setModel(new TabelDetaiModel());
            calculate();
        }
    }//GEN-LAST:event_btnTambahPDActionPerformed

    private void btnEditPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPDActionPerformed
        // TODO add your handling code here:
        if(selectedPembelian !=null){
            selectedPembelian=new PembelianLooKDialog().showDialog(selectedPembelian);
            tblPembelian.tableChanged(new TableModelEvent(tblPembelian.getModel(), tblPembelian.getSelectedRow()));
            calculate();
        }else{
            JOptionPane.showMessageDialog(Main.getFrame(), "Pilih Pembelian Detail","WARNING", JOptionPane.WARNING_MESSAGE, getFrameIcon());
        }
    }//GEN-LAST:event_btnEditPDActionPerformed

    private void btnHapusPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPDActionPerformed
        // TODO add your handling code here:
        if(selectedPembelian !=null){
            details.remove(selectedPembelian);
            tblPembelian.setModel(new TabelDetaiModel());
            calculate();
            selectedPembelian=null;
        }else{
            JOptionPane.showMessageDialog(Main.getFrame(), "Pilih Pembelian Detail", "WARNING",JOptionPane.WARNING_MESSAGE, getFrameIcon());
        }
    }//GEN-LAST:event_btnHapusPDActionPerformed

    private void btnTambahPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPActionPerformed
        // TODO add your handling code here:
        enableDetaiForm(true);
        txtTGL.setDate(new Date());
        
    }//GEN-LAST:event_btnTambahPActionPerformed

    private void btnSimpanPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPActionPerformed
        // TODO add your handling code here:
        if(pembelian ==null) pembelian=new Pembelian();
        
        loadFormToModel();
        try{
            Main.getTransaksiService().simpan(pembelian);
           
        }catch(StaleObjectStateException ex){
            JOptionPane.showMessageDialog(Main.getFrame(), "Data sudah di update user lain","WARNING", JOptionPane.WARNING_MESSAGE,getFrameIcon());
            log.error("Gagal simpan pembelian", ex);
        }
        pembelian=null;
        bersih();
        enableDetaiForm(false);
    }//GEN-LAST:event_btnSimpanPActionPerformed

    private void btnKeluarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarPActionPerformed
        // TODO add your handling code here:
        Main.getFrame().frmPembelian=null;
        dispose();
    }//GEN-LAST:event_btnKeluarPActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        Main.getFrame().frmPembelian=null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnCariPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPActionPerformed
        // TODO add your handling code here:
        Pembelian p= new PembelianSearchDialog().showDialog();
        if(p!=null){
            pembelian=Main.getTransaksiService().getIdPembelian(p.getId());
            loadDomainToForm();
        }
    }//GEN-LAST:event_btnCariPActionPerformed

    private void btnHapusPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPActionPerformed
        // TODO add your handling code here:
        if(pembelian !=null){
            int hps= JOptionPane.showConfirmDialog(Main.getFrame(),"Yakin hapus Data","CONFIRM",JOptionPane.OK_CANCEL_OPTION ,JOptionPane.QUESTION_MESSAGE, getFrameIcon());
               if(hps==0){ 
                Main.getTransaksiService().hapus(pembelian);
                pembelian=null;
                selectedPembelian=null;
                details.clear();
                enableDetaiForm(false);
                bersih();
               }
        }else{
            JOptionPane.showMessageDialog(Main.getFrame(), "Pilih Data lewat tombol cari", "WARNING", JOptionPane.WARNING_MESSAGE,getFrameIcon());
        }
        
    }//GEN-LAST:event_btnHapusPActionPerformed
    
    private class TabelDetaiModel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return details.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            PembelianDetail p = details.get(rowIndex);
            switch(columnIndex){
                case 0 : return p.getProduk().getNama();
                case 1 : return p.getHarga();
                case 2 : return p.getJumlah();
                case 3 : return p.getSubTotal();
                default : return "";
            }
        }
        
    }
    
    private class TabelDetailListener implements ListSelectionListener{

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if(tblPembelian.getSelectedRow()>=0){
                int index=tblPembelian.convertRowIndexToModel(tblPembelian.getSelectedRow());
                selectedPembelian=details.get(index);
            }
        }
        
    }
    
    private void calculate(){
        BigDecimal total=BigDecimal.ZERO;
        for(PembelianDetail p : details){
            total=total.add(p.getSubTotal());
        }
        txtTotal.setText(UtilityTools.formatNumber(total));
    }
    
    private void bersih(){
        txtID.setText("");
        txtTotal.setText("");
        txtTGL.setDate(new Date());
        details.clear();
        tblPembelian.setModel(new TabelDetaiModel());
    }
    
    private void enableDetaiForm(boolean status){
        btnTambahPD.setEnabled(status);
        btnEditPD.setEnabled(status);
        btnHapusPD.setEnabled(status);
        txtTotal.setEditable(false);
        txtTGL.setEnabled(false);
        
    }
    
//    Meload data dari doamain ke form
    private void loadDomainToForm(){
        txtID.setText(String.valueOf(pembelian.getId()));
        txtTGL.setDate(pembelian.getTgl_beli());
        txtTotal.setText(UtilityTools.formatNumber(pembelian.getTotal()));
        details=pembelian.getPembelianDetail();
        tblPembelian.setModel(new TabelDetaiModel());
    }
//    Meload data dari form ke model
    private void loadFormToModel(){
        pembelian.setTgl_beli(txtTGL.getDate());
        pembelian.setTotal(UtilityTools.parseNumberToBigDecimal(txtTotal.getText()));
        pembelian.setPembelianDetail(details);
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalP;
    private javax.swing.JButton btnCariP;
    private javax.swing.JButton btnEditP;
    private javax.swing.JButton btnEditPD;
    private javax.swing.JButton btnHapusP;
    private javax.swing.JButton btnHapusPD;
    private javax.swing.JButton btnKeluarP;
    private javax.swing.JButton btnSimpanP;
    private javax.swing.JButton btnTambahP;
    private javax.swing.JButton btnTambahPD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblPembelian;
    private javax.swing.JTextField txtID;
    private com.toedter.calendar.JDateChooser txtTGL;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
